 services:
  frontend:
    build: .
    environment:
      - NODE_ENV=production
      - APP_PORT=${APP_PORT}
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
      - NEXT_PUBLIC_SERVER_WEBSOCKET_URL=${NEXT_PUBLIC_SERVER_WEBSOCKET_URL}
    ports: 
      - "3000:3000"
    command: npm run start
    
    networks:
      - fund-maker-network

    restart: always