 services:
  frontend:
    volumes:
      - .:/app
      - /app/node_modules
    build: .
    environment:
      - NODE_ENV=development
      - APP_PORT=${APP_PORT}
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
      - NEXT_PUBLIC_SERVER_WEBSOCKET_URL=${NEXT_PUBLIC_SERVER_WEBSOCKET_URL}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports: 
      - "3000:3000"
    command: npm run dev
    
    networks:
      - fund-maker-network