 services:
  frontend:
    volumes:
      - ./app:/app/app
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
    build: .
    environment:
      - NODE_ENV=development
      - APP_PORT=${APP_PORT}
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
      - NEXT_PUBLIC_ORDERBOOK_SERVER_WEBSOCKET_URL=${NEXT_PUBLIC_ORDERBOOK_SERVER_WEBSOCKET_URL}
      - NEXT_PUBLIC_BACKEND_SERVER_WEBSOCKET_URL=${NEXT_PUBLIC_BACKEND_SERVER_WEBSOCKET_URL}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports: 
      - "3000:3000"
    command: npm run fast
    
    networks:
      - fund-maker-network
    
    restart: always