export enum IndexStatusEnum {
  PROCESSING = "PROCESSING",
  SUCCESS_HISTORICAL = "SUCCESS_HISTORICAL",
  PROCESSING_LIVE = "PROCESSING_LIVE",
  ERROR_NO_REBALANCE_DATA = "ERROR_NO_REBALANCE_DATA",
  ERROR_NO_CANDLES_DATA = "ERROR_NO_CANDLES_DATA",
  ERROR_NO_MARLETCAP_DATA = "ERROR_NO_MARLETCAP_DATA",
}
